version: 0.0
os: linux
files:
    - source: /
      destination: /apps/react
hooks:
  BeforeInstall:
    - location: scripts/install_depencies.sh
      timeout: 180
  ApplicationStop:
   - location: scripts/stop_server.sh
     timeout: 180
  ApplicationStart:
    - location: deployment/install_service.sh
      timeout: 180
