version: 0.0
os: linux
files:
    - source: /
      destination: /apps/react
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/install_service.sh
      timeout: 180
